### ISSUE TITLE
Why only pgpool 9.3?

### ISSUE THREAD

**Issue by khdevel** [mwhahaha/puppet-pgpool#15]
Hello,

I am using _postgresql94_ and I wanted to use the same pgpool release (9.4) but it seems that the version 9.3 is hardcoded in e.g. config/service.pp.

Could you please fix it and make possible to determine the release by the user?

The files with _pgpool-II-93_ are:
- modules/pgpool/spec/classes/init_spec.rb
- modules/pgpool/README.md
- modules/pgpool/manifests/config/service.pp
- modules/pgpool/manifests/init.pp

Thank you,
Kamil

**Comment by mwhahaha** [comment]
If you specify the postgres version as 9.4 it will pull I'm that version. I will double check the code but at first glance you just need to pass n postgres_version => '9.4' and it should work.

**Comment by khdevel** [comment]
Maybe you are right here, I will check it and let you know about the results but I am worry about something like this in _service.pp_:

```
class pgpool::config::service (
  $pid_file_name = '/var/run/pgpool-II-93.pid',
  $logdir        = '/var/log/pgpool-II-93',
)
```

Will this '93' change to '94' in case I use the latest _postgres94_?

Let me check...

**Comment by khdevel** [comment]
It seems that everything is fine and works like you wrote!
Thank you for the module and sorry for inconvenience.
